<?php
/** GET /api/export.php?project_id=N  → downloadable README.md (text/markdown) */

// This endpoint returns markdown, not JSON, so it does not use _lib.php.
ini_set('display_errors', '0');
error_reporting(E_ERROR | E_PARSE);
require_once dirname(__FILE__) . '/config.php';

header('Access-Control-Allow-Origin: *');

$id = isset($_GET['project_id']) ? (int) $_GET['project_id'] : (isset($_GET['id']) ? (int) $_GET['id'] : 0);
if ($id <= 0) { header('HTTP/1.1 400 Bad Request'); echo 'Invalid project id'; exit; }

$pr = $DB->query("SELECT project_id, project_name, repository_url, created_at FROM projects WHERE project_id=" . (int) $id);
if (!$pr || $pr->num_rows === 0) { header('HTTP/1.1 404 Not Found'); echo 'Project not found'; exit; }
$p = $pr->fetch_assoc();

// Include the overview column only if it exists (graceful before the ALTER).
$hasOverview = false;
$cc = $DB->query("SHOW COLUMNS FROM project_metadata LIKE 'overview'");
if ($cc && $cc->num_rows > 0) { $hasOverview = true; }
$metaCols = $hasOverview
    ? "server_location, tech_stack, functional_purpose, overview"
    : "server_location, tech_stack, functional_purpose";

$meta = null;
$mr = $DB->query("SELECT $metaCols FROM project_metadata WHERE project_id=" . (int) $id);
if ($mr) { $meta = $mr->fetch_assoc(); }

$docs = array();
$dr = $DB->query("SELECT file_name FROM project_documents WHERE project_id=" . (int) $id . " ORDER BY created_at ASC");
if ($dr) { while ($d = $dr->fetch_assoc()) { $docs[] = $d['file_name']; } }

$pending = 'pending';
function fmt_val($v, $pending) {
    return (!$v || $v === $pending) ? '_Not yet generated — run the AI summary._' : $v;
}

$techStack = '_Not yet generated._';
if ($meta && isset($meta['tech_stack']) && $meta['tech_stack'] !== '' && $meta['tech_stack'] !== $pending) {
    $lines = array();
    foreach (explode(',', $meta['tech_stack']) as $t) { $lines[] = '- ' . trim($t); }
    $techStack = implode("\n", $lines);
}

$docList = '_No documents uploaded._';
if (count($docs) > 0) {
    $dl = array();
    foreach ($docs as $f) { $dl[] = '- `' . $f . '`'; }
    $docList = implode("\n", $dl);
}

$md  = "# " . $p['project_name'] . "\n\n";
$md .= "> Turnover summary generated by the Project Turnover Summary & Debugging Assistant.\n\n";
// repository_url is a JSON array of URLs.
$repoUrls = array();
if (!empty($p['repository_url'])) {
    $dec = json_decode($p['repository_url'], true);
    if (is_array($dec)) { $repoUrls = array_values(array_filter($dec, 'strlen')); }
    else { $repoUrls = array($p['repository_url']); }
}
if (count($repoUrls)) {
    $md .= "**Repositories:**\n";
    foreach ($repoUrls as $u) { $md .= "- " . $u . "\n"; }
    $md .= "\n";
}
$md .= "## Functional Purpose\n\n" . fmt_val($meta ? $meta['functional_purpose'] : '', $pending) . "\n\n";
$md .= "## Tech Stack\n\n" . $techStack . "\n\n";
$md .= "## Server / Environment Location\n\n" . fmt_val($meta ? $meta['server_location'] : '', $pending) . "\n\n";

// Full AI overview (Architecture, Entry Points, How to Run Locally, Gotchas...)
$overview = ($meta && isset($meta['overview'])) ? trim($meta['overview']) : '';
if ($overview !== '') {
    $md .= "## Overview\n\n" . $overview . "\n\n";
}

$md .= "## Source Documents\n\n" . $docList . "\n\n";
$md .= "---\n_Created: " . $p['created_at'] . "_\n";

$fileName = preg_replace('/[^\w.\-]+/', '_', $p['project_name']) . '-README.md';
header('Content-Type: text/markdown; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $fileName . '"');
echo $md;
?>
